version: 2.1
jobs:
  build:
    docker:
      - image: node:10.16-alpine
    steps:
      - checkout
      - run:
          name: 'Install SDK dependencies'
          command: 'npm ci'
      - run:
          name: 'Build SDK'
          command: 'npm run build'
      - run:
          name: 'Install test dependencies'
          command: 'cd test/e2e && npm ci'
      - run:
          name: 'E2E tests'
          command: 'npm test'