const { resources, getScope, setupForApiVersion2, teardown  } = require('./util')
const evrythng = require('../..')

 const a = evrythng.setup({geolocation: false })
 console.log(a)
 process.on('unhandledRejection', console.error)

describe.only('evrythng.js', () => {
  before(setupForApiVersion2)

  describe('as Operator', () => {
   // require('./entity/accessTokens.spec')()
    require('./entity/accesses.spec')('operator')
    // require('./entity/accountRedirector.spec')()
    // require('./entity/accounts.spec')()
    // require('./entity/actions.spec')('operator')
    // require('./entity/actionTypes.spec')('operator')
    // require('./entity/adiOrders.spec')()
    // require('./entity/applicationRedirector.spec')()
    // require('./entity/applications.spec')('operator')
    // require('./entity/batches.spec')()
    // require('./entity/commissionState.spec')('operator')
    // require('./entity/collections.spec')('operator')
    // require('./entity/domains.spec')()
    // require('./entity/files.spec')('operator')
    // require('./entity/locations.spec')('operator')
    // require('./entity/permissions.spec')('operator')
    // require('./entity/permissions.spec')('userInApp')
    // require('./entity/places.spec')('operator')
    // require('./entity/products.spec')('operator')
    // require('./entity/projects.spec')()
    // require('./entity/properties.spec')('operator', 'product')
    // require('./entity/properties.spec')('operator', 'thng')
    // require('./entity/purchaseOrders.spec')('operator')
    // require('./entity/reactor.spec')('operator')
    // require('./entity/redirection.spec')('operator', 'product')
    // require('./entity/redirection.spec')('operator', 'thng')
    // require('./entity/roles.spec')('operator')
    // require('./entity/rules.spec')()
    // require('./entity/secretKey.spec')()
    // require('./entity/shipmentNotice.spec')()
    // require('./entity/shortDomains.spec')()
    // require('./entity/tasks.spec')()
    // require('./entity/thngs.spec')('operator')
    // require('./entity/user.spec')('operator')
  })
  describe.skip('Misc', () => {
    require('./misc/alias.spec')()
    require('./misc/api.spec')('operator')
    require('./misc/find.spec')()
    require('./misc/pages.spec')('operator')
    require('./misc/paramSetters.spec')()
    require('./misc/rescope.spec')()
    require('./misc/stream.spec')()
    require('./misc/streamPages.spec')()
    require('./misc/upsert.spec')()
    require('./misc/use.spec')()
  })
})
