const { resources, setupForApiVersion2, teardown  } = require('./util')
const evrythng = require('../../dist/evrythng.node')


const settings = evrythng.setup({ apiVersion: 2, geolocation: false })
 process.on('unhandledRejection', console.error)

  describe.only('evrythng.js', () => {
    
  before(async () => {
    const a = setupForApiVersion2(settings.apiUrl)
  })

  describe('as Operator', () => {
    const operatorScope = 'operator'
    require('./entity/accessPolicies.spec')(operatorScope, settings)
    require('./entity/accessTokens.spec')(operatorScope, settings)
    require('./entity/accountRedirector.spec')(operatorScope, settings.apiUrl)
    require('./entity/accounts.spec')(operatorScope, settings.apiUrl)
    require('./entity/actions.spec')(operatorScope, settings.apiUrl)
    require('./entity/actionTypes.spec')(operatorScope, settings.apiUrl)
    require('./entity/adiOrders.spec')(operatorScope, settings.apiUrl)
    require('./entity/adiOrderEvents.spec')(operatorScope, settings.apiUrl)
    require('./entity/applicationRedirector.spec')(operatorScope, settings.apiUrl)
    require('./entity/applications.spec')(operatorScope, settings.apiUrl)
    require('./entity/batches.spec')(operatorScope, settings)
    require('./entity/collections.spec')(operatorScope, settings.apiUrl)
    require('./entity/commissionState.spec')(operatorScope, settings.apiUrl)
    require('./entity/domains.spec')(operatorScope, settings.apiUrl)
    //require('./entity/files.spec')(operatorScope, settings.apiUrl)
    require('./entity/locations.spec')(operatorScope, settings.apiUrl)
    //require('./entity/me.spec')()
    //require('./entity/operatorAccesses.spec')()
    require('./entity/places.spec')(operatorScope, settings.apiUrl)
    require('./entity/products.spec')(operatorScope, settings.apiUrl)
    require('./entity/projects.spec')(operatorScope, settings.apiUrl)
    require('./entity/properties.spec')(operatorScope, 'product',  settings.apiUrl)
    require('./entity/properties.spec')(operatorScope, 'thng', settings.apiUrl)
    require('./entity/purchaseOrders.spec')(operatorScope, settings.apiUrl)
    require('./entity/reactor.spec')(operatorScope, settings.apiUrl)
    require('./entity/redirection.spec')(operatorScope, 'product')
    require('./entity/redirection.spec')(operatorScope, 'thng')
    // require('./entity/roles.spec')('operator')
    // require('./entity/rules.spec')()
    // require('./entity/secretKey.spec')()
    require('./entity/shipmentNotice.spec')(operatorScope, settings.apiUrl)
    require('./entity/shortDomains.spec')(operatorScope, settings.apiUrl)
    // require('./entity/tasks.spec')()
    require('./entity/thngs.spec')(operatorScope, settings.apiUrl)
    // require('./entity/user.spec')('operator')
  })
  describe.skip('Misc', () => {
    require('./misc/alias.spec')()
    require('./misc/api.spec')('operator')
    require('./misc/find.spec')()
    require('./misc/pages.spec')('operator')
    require('./misc/paramSetters.spec')()
    require('./misc/rescope.spec')()
    require('./misc/stream.spec')()
    require('./misc/streamPages.spec')()
    require('./misc/upsert.spec')()
    require('./misc/use.spec')()
  })
})
